### ISSUE TITLE
Connect to OSRM vectortiles service

### ISSUE THREAD

**Issue by Doev** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#284]
How can I connect the Plugin to the tiles service of OSRM?

http://project-osrm.org/docs/v5.5.1/api/#tile-service

**Comment by sfkeller** [comment]
From the FAQ: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin#faq
> you have to create a connection using a URL pointing to the TileJSON of the tile service

**Comment by Doev** [comment]
Thank you for the repley. My problem is, that I can't find out, how the TileJSON URLS is, or if there is any. So this means with the given URL it is not possible?

/tile/v1/{profile}/tile({x},{y},{zoom}).mvt
http://router.project-osrm.org/tile/v1/car/tile(1310,3166,13).mvt

**Comment by pelord** [comment]
any updates?

**Comment by sfkeller** [comment]
Thanks for reminding. I'm closing this issue with following comment: 

First, the "Vector-Tiles-Reader-QGIS-Plugin" has been superseeded since QGIS 3.14 version by it's native support for loading of vector tiles.  See e.g. https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector_tiles/vector_tiles_properties.html

Second, pls. open an issue over at OSRM https://github.com/Project-OSRM/osrm-backend/issues/2980 asking if they ever tested QGIS as client to their nice routing engine.
