### ISSUE TITLE
Nextzen.org (default entry with credits) is not loading | Error The field 'vector_layers' is required but not found. This is invalid TileJSON.

### ISSUE THREAD

**Issue by piozia98** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#291]
The field 'vector_layers' is required but not found. This is invalid TileJSON.
![image](https://user-images.githubusercontent.com/102856924/214608569-a251e431-b696-4462-8ff2-2045b2878474.png)

**Comment by sfkeller** [comment]
Hi,

I think that the error message of the plugin is clear and correct: So pls. contact Nextzen.org about this error :-).

But even more important: Note that the "Vector-Tiles-Reader-QGIS-Plugin" has been superseeded since QGIS 3.14 version by a native support for loading of vector tiles. See e.g. https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector_tiles/vector_tiles_properties.html

Yours, Stefan
