### ISSUE TITLE
Tile server - fundamental question about plugin functionality

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#36]
How does this work with tileservers? (this question also applies to local mbtiles, but the server issue is the more important one.)

Tiles, whether raster or vector, exist to allow chunking/streaming of big data to the client. This entails the following two broad actions:

1. Only load what is required
2. Unload what is no longer required

Does this plugin do this? Or does it simply pull in everything, or everything which intersects the current QGIS canvas bounds?

**Comment by mnboos** [comment]
The plugin loads the current QGIS canvas bounds. Due to the vast amount of data this can result in, the plugin provides functionality to limit the number of tiles to be loaded.

Unloading no longer required data would mean, to remove this layers from QGIS. I think that would heavily infere with a proper user experience and therefore such an auto-remove feature is not implemented.

However, performance is still an issue that will be addressed by some caching mechanism soon. I'm open for suggestions regarding this matter.

**Comment by tomchadwin** [comment]
I'm just concerned that this means the plugin would not be usable for common tileserver situations. As in, it would be usable to load as a one-off, but people's expectations for tiles are as I described. Ideally, the workflow should be something along the lines of:

1. Load the tiles which intersect with the viewport
2. Listen for pan/zoom etc events
3. On pan/zoom etc load in the tiles which now intersect the viewport, not as new layers, but merged into the existing layers where they already exist

Set some sensible storage threshold, and on pan/zoom, if that storage has been exceeded, delete the features which were loaded furthest in the past.

**Comment by sfkeller** [comment]
Keep in mind that this plugin is originally designed to serve as an VT inspection and debugging tool. Initially, some people did'nt believe that such a VT reader is possible at all.

But your concerns about performance and resource efficiency are valid. We are aware of that and we could assign a separate sprint to that.

**Comment by sfkeller** [comment]
See also #26 .

**Comment by mnboos** [comment]
Closing this. Feel free to reopen, if there's any necessity.
