### ISSUE TITLE
Categorized layers better than layer groups?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#38]
I don't know the answer to this, but perhaps it would be better if a smaller number of categorized layers were created, and then a categorized renderer applied. For example, at the moment, a `place` layer group is created with layers `suburb`, `hamlet`, etc. Would it not be tidier to make `place` a layer, with `suburb`, `hamlet` etc as categories?

**Comment by mnboos** [comment]
As a result of a smaller QGIS layer hierarchy, the loading process is significantly faster in some cases, as fewer layers have to be created and processed by QGIS. On the other hand, due to the new layering, additional time concerning the styling has to be invested, as I have to create new, rule-based styles and most of the current styles would be obsolete.

Personally, I would invest the time into the styling and profit from the loading performance.

@sfkeller What's your opinion in this masster?

The new hierarchy in QGIS would lookk something like this:
![image](https://cloud.githubusercontent.com/assets/22575883/25553921/9e9448cc-2cc0-11e7-85d6-c12161c5de04.png)

**Comment by sfkeller** [comment]
I think users profit from a readable style whereas the focus of this semester thesis is of course SW engineering and dev. Actually since performance is a big issue here, the new layering and thus a bit more work in styling is a good investment. So, go ahead in styling like labels, scale dependent parameters, rule-based styles, etc.

**Comment by sfkeller** [comment]
Making a readable style get's more insights about an automated default style generator. 

In any case keep an eye on the "cartographic elements" ordering "label, point/line/area signatures, then raster (in the screenshot above there's the poi layer which is point type and should be moved almost to the top). In case labels are attachted to point/line/area there's the possibility in QGIS to activate the "Layer Order Panel".

Rule-based makes rendering slower, but I think we can afford that . See also the [OSMaxx style](https://osmaxx.hsr.ch/pages/downloads/).

**Comment by mnboos** [comment]
The layer order results from your suggestion that you sent me per mail:
![cartographic_ordering_stefan](https://cloud.githubusercontent.com/assets/22575883/25554215/ebef7464-2cc7-11e7-95af-93ece3d2074f.png)

**Comment by sfkeller** [comment]
Right, sorry, so poi seems to the topmost point layer just before the "label layers".

**Comment by tomchadwin** [comment]
Glad you both think its worth investigating. Main difficulty in implementation is that the only groups which should be turned into categorized layers are those which have only direct children - no grandchildren, etc. That will take a little work to achieve.

**Comment by mnboos** [comment]
Closing this, as the new layering is sufficing at the moment.
