### ISSUE TITLE
Handle invalid geometries when merging features over tile boundaries

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#4]
The current approach is working as long as there are only valid geometries. However, in case of null geometries, creating an intersection layer in QGIS using processing won't work. A solution would be to clean the layer in prior, using grass7:v.clean. Unfortunately, there is a bug in qgis which makes it impossible to use this plugin from python code (https://hub.qgis.org/issues/16195)

**Comment by mnboos** [comment]
Current workaround: Use qgis "Check validity" tool.
Impact: The invalid features are not fixed but just removed.

**Comment by sfkeller** [comment]
I strongly recommend not to use non-core libraries like GRASS or SAGA (even though they are great and well respected software). Reason is to lower dependencies (there are many QGIS installations without them) and because both are rather large in size.

A null geometry is (luckily) not the same as an invalid geometry. A null geometry should be much easierr to detect than an invalid geometry. 

Aren't null geometries just null features (no geom. but also no attributes) and is isn't it simply NULL when querying mbtiles and HTTP Error 404 when using GET z/x/y?

**Comment by mnboos** [comment]
I think I confused NULL geometries with invalid ones. The null geometries are being ignored when creating the intersection layer.

**Comment by mnboos** [comment]
What I figured out: QGIS cannot handle geometries with at least one inner ring that is located outside of the exterior ring. To fix this problem, these geometries have to be split to multiple features (e.g. one for the exterior ring, one for the inner ring). Winding order should be irrelevant in this case, the inner ringe doesn't represent a hole anyways.

![invalid geometry](https://cloud.githubusercontent.com/assets/22575883/23837152/1d23332c-0784-11e7-9739-3d88eef32afd.png)

**Comment by sfkeller** [comment]
QGIS is correct: An interior ring is *always* inside an exterior one. 
That's according to computational geometry and GIS standards like OGC SFA: http://www.opengeospatial.org/standards/sfa and/or http://www.interlis.ch/interlis2/docs23/ili2-refman_2006-04-13_e.pdf .

Is this "interior ring" perhaps part of another exterior one - or part of the same large polygon before it was clipped?

**Comment by mnboos** [comment]
It belonged to the same polygon, before it was separated during tile generation.

![image](https://cloud.githubusercontent.com/assets/22575883/23843551/faec06f6-07bc-11e7-9156-453e7e0b882f.png)

**Comment by mnboos** [comment]
Due to the improved tile-merging, its no longer necessary to fix invalid geometries. QGIS will show them anyway.
