### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#41]
There are several other plugins dealing at various levels with tiles. Please make it clear in the About what makes this plugin necessary.
Also it would be appreciated if you could explore the possibility of merging your work with some of the existing plugins.

**Comment by mnboos** [comment]
This plugin has already been accepted in the QGIS plugins repository. I had to delete and re-add it in order to change the folder name inside the zip-archive.

However; this plugin enables a QGIS user to read vector tiles from either a file or a tile-server which serves vector tiles (e.g. http://openmaptiles.org). I don't see any other plugins that support vector tiles from files or servers.

**Comment by pcav** [comment]
Thanks for the clarification. Now reapproved.
